### ISSUE TITLE
Inconsistent Shortname - feet/footprints

### ISSUE THREAD

**Issue by DavidJFelix** [emojione/emojione#182]
In EmojiOne the shortname is `:footprints:` but http://www.emoji-cheat-sheet.com/ seems to call this Emoji `:feet:`

**Comment by mikebe11** [comment]
I don't know why emoji-cheat-sheet.com has a different shortname for those. We're in line with the majority of references and products out there (ex. http://emojipedia.org/ & http://www.iemoji.com/). I don't see us changing those shortnames at this time.

**Comment by DavidJFelix** [comment]
seems like mattermost and gitter call this emoji ":feet:". Slack seems to call what emojione calls ":paw_prints:" as ":feet:". I'll look into campfire and others. It's odd that there are such similar names and not a ton of agreement.

**Comment by DavidJFelix** [comment]
oops. github seems to agree with slack, but also accept paw prints. I'll edit above and leave the old message for posterity.

**Comment by DavidJFelix** [comment]
Chart for tracking. I'll add as more show up.

| platform | `:feet:` | `:footprints:` | `:paw_prints:`|
| ---------- | --------- | --------------- | ----------------- |
| github | :feet: | :footprints: | :feet: |
| gitter | :footprints: | n/a | :feet: |
| slack | :feet: | :footprints: | :feet: |
| mattermost | :footprints: | n/a | :feet: |

**Comment by mikebe11** [comment]
It is odd there isn't much agreement on these names. The founder is working on developing an organization to address the lack of standards like we see here. This type of data will be helpful I'm sure. In the meantime we do have shortname aliases in our data. `:paw_prints:` can be added as an alias for :feet:

**Comment by DavidJFelix** [comment]
Reverse-linking the above links:

https://github.com/arvida/emoji-cheat-sheet.com/issues/351
https://github.com/gitterHQ/gitter/issues/1047
https://github.com/mattermost/platform/issues/1803
