### ISSUE TITLE
Safari (desktop and iOS) svg sprites unusable

### ISSUE THREAD

**Issue by emilhauk** [emojione/emojione#232]
Please see example: http://itoken.no/emojione/ (had to do this on a private server to overcome CORS for the svg-file)

In Chrome this works as expected, but Safari (desktop or phone/pad) consumes a hefty amount of memory and is incredibly slow.

**Comment by mikebe11** [comment]
@emilhauk This issue with Safari may be new and doesn't appear to be just related to our sprite sheet.

https://github.com/jonathantneal/svg4everybody/issues/110

**Comment by emilhauk** [comment]
Ah, thank you. Did not see that issue on svg4everybody.
