### ISSUE TITLE
Too many files per folder for Github

### ISSUE THREAD

**Issue by Crissov** [emojione/emojione#326]
- [./assets/png](https://github.com/Ranks/emojione/tree/master/assets/png),
- [./assets/png_128x128](https://github.com/Ranks/emojione/tree/master/assets/png_128x128),
- [./assets/png_512x512](https://github.com/Ranks/emojione/tree/master/assets/png_512x512),
- [./assets/svg](https://github.com/Ranks/emojione/tree/master/assets/svg):

> Sorry, we had to truncate this directory to 1,000 files. 832 entries were omitted from the list.

Maybe you should put character sequences (VS-16, ZWJ, Fitzpatrick Modifier, flags) into sub-folders.

**Comment by caseyahenson** [comment]
Moved to emojione-assets. @Crissov this is definitely the direction we're headed in. We've already split sprites into categories which has greatly reduced the size of those. We may shoot for this in the 3.1 update.
