### ISSUE TITLE
Provide Head and Body Images for all Animals

### ISSUE THREAD

**Issue by Crissov** [emojione/emojione#419]
Vendors disagree about how to display animal emojis that do not come in a pair of two,  _ANIMAL_ and _ANIMAL_ FACE. For almost every solitary _ANIMAL_ or _ANIMAL_ FACE emoji you’ll find both, an example of a full-body glyph and an example of a head-only glyph. Please make Emojione the first implementation that offers users the choice between them by providing both views as pictures.

In the Opentype font, these would be accessed through (individual) `cv##` or (collective) `ss##` features (or both). Other formats would require different techniques.

## Examples

- [Dromedary Camel] 🐪 is shown as a camel’s head in Emojione, while the [Bactrian Camel] 🐫 has its full body, with 2 humps. #357
- [Bear] 🐻, [Panda] 🐼, [Lion] 🦁, [Fox] 🦊, [Frog] 🐸, [Hamster] 🐹, [Wolf] 🐺, [Unicorn] 🦄 have FACE in their name and are usually displayed as heads.
- [Koala] 🐨, [Boar] 🐗, [Penguin] 🐧, [Bird] 🐦, [Chick] 🐤🐥 and [Chicken] 🐔 are sometimes shown portrait-only, by Apple in particular – and they are grouped together in the GUI for this reason. 
- Unicode 9 animals [Gorilla] 🦍, [Deer] 🦌, [Rhinoceros] 🦏 and [Eagle] 🦅 do *not* feature FACE in their names, but are displayed as heads in several implementations, including Emojione. (The rhino is the only mammal head not facing the reader in Emojione!) Apple and Microsoft disagree. #339 
- Some other animals, e.g. [Ram] 🐏, [Sheep] 🐑 and [Goat] 🐐 or [Elephant] 🐘 ~~and [Crocodile] 🐊~~ are also sometimes shown as heads. All of these are used as Asian Zodiac signs.
- It’s unclear how vendors will handle new animal emojis coming to Unicode 10 in June 2017: [Giraffe] &#x1F992;, [Zebra] &#x1F993;, [Hedgehog] &#x1F994;, [Sauropod] &#x1F995; and [T-Rex] &#x1F996;.
- Many other large animals come in explicit pairs, [Dog]/[Poodle] 🐶/🐕🐩, [Cat] 🐱/, [Mouse]/[Rat] 🐭/🐀🐁, [Rabbit]/Bunny/Hare 🐰/🐇, [Tiger]/[Leopard] 🐯/🐅🐆, [Cow]/[Ox]/[Water Buffalo] 🐮/🐄🐂🐃, [Pig] 🐽/🐷/🐖, [Monkey] 🐵🙈🙉🙊/🐒, [Horse] 🐴/🐎🏇🎠, [Dragon] 🐲/🐉.

  [Dromedary Camel]: http://emojipedia.org/dromedary-camel/
  [Bactrian Camel]: http://emojipedia.org/bactrian-camel/

  [Bear]: http://emojipedia.org/bear-face/
  [Panda]: http://emojipedia.org/panda-face/
  [Lion]: http://emojipedia.org/lion-face/
  [Fox]: http://emojipedia.org/fox-face/
  [Frog]: http://emojipedia.org/frog-face/
  [Hamster]: http://emojipedia.org/hamster-face/
  [Wolf]: http://emojipedia.org/wolf-face/
  [Unicorn]: http://emojipedia.org/unicorn-face/

  [Koala]: http://emojipedia.org/koala/
  [Boar]: http://emojipedia.org/boar/
  [Penguin]: http://emojipedia.org/penguin/
  [Bird]: http://emojipedia.org/bird/
  [Chick]: http://emojipedia.org/chick/
  [Chicken]: http://emojipedia.org/chicken/
  [Gorilla]: http://emojipedia.org/gorilla/
  [Deer]: http://emojipedia.org/deer/
  [Rhinoceros]: http://emojipedia.org/rhinoceros/
  [Eagle]: http://emojipedia.org/eagle/

  [Ram]: http://emojipedia.org/ram/
  [Sheep]: http://emojipedia.org/sheep/
  [Goat]: http://emojipedia.org/goat/
  [Elephant]: http://emojipedia.org/elephant/
  [Crocodile]: http://emojipedia.org/crocodile/

  [Giraffe]: http://emojipedia.org/giraffe-face/
  [Zebra]: http://emojipedia.org/zebra-face/
  [Hedgehog]: http://emojipedia.org/hedgehog/
  [Sauropod]: http://emojipedia.org/sauropod/
  [T-Rex]: http://emojipedia.org/t-rex/

  [Dog]: http://emojipedia.org/dog/
  [Poodle]: http://emojipedia.org/poodle/
  [Cat]: http://emojipedia.org/cat/
  [Mouse]: http://emojipedia.org/mouse/
  [Rat]: http://emojipedia.org/rat/
  [Rabbit]: http://emojipedia.org/rabbit/
  [Tiger]: http://emojipedia.org/tiger/
  [Leopard]: http://emojipedia.org/leopard/
  [Cow]: http://emojipedia.org/cow/
  [Ox]: http://emojipedia.org/ox/
  [Water Buffalo]: http://emojipedia.org/water-buffalo/
  [Pig]: http://emojipedia.org/pig/
  [Monkey]: http://emojipedia.org/monkey/
  [Horse]: http://emojipedia.org/horse/
  [Dragon]: http://emojipedia.org/dragon/

**Comment by Crissov** [comment]
On a related note, some (team/competitive) sports emojis should also come with options. Some vendors display [Basketball and Hoop 🏀](http://emojipedia.org/basketball-and-hoop/) or [Tennis Racquet and Ball 🎾](http://emojipedia.org/tennis-racquet-and-ball/) or [Billiards 🎱](http://emojipedia.org/billiards/) as just the ball, for instance.

| Sport | Player / Athlete | Tool / Vehicle / Clothes | Object / Ball | Goal / Target / Net / Obstacle | 
|------|------|------|------|------|
| Association Football | ⛹ |  | ⚽&#xfe0f; | 🥅 |
| American Football |  |  | 🏈 |  |
| Rugby Football |  |  | 🏉 |  |
| Handball | &#x1f93e; |  |  |  |
| Volleyball | ⛹ |  | 🏐 |  |
| Basketball | ⛹ |  | 🏀 | 🏀 |
| Baseball / Softball |  |  | ⚾&#xfe0f; |  |
| Cricket |  | 🏏 | 🏏 |  |
| Ice Hockey |  | 🏒⛸ | 🏒 |  |
| Field Hockey |  | 🏑 | 🏑 |  |
| Polo |  | 🏇🐎🐴🏑 | 🏑 |  |
| Water Polo | &#x1f93d; &#x1f3ca; |  |  |  |
| Tennis |  | 🎾 | 🎾 |  |
| Tabletennis |  | 🏓 | 🏓 |  |
| Badminton |  | 🏸 | 🏸 |  |
| Golf | 🏌 |  |  | ⛳&#xfe0f;🚩🕳 |
| Billiards / Snooker |  | 🎱 | 🎱 |  |
| Archery |  | 🏹 | 🏹💘 | 🎯 |
| Darts |  | 🎯 | 🎯 | 🎯 |
| Bowling |  |  | 🎳 | 🎳 |
| Boxing |  | 🥊 |  |  |
| Fencing | 🤺 | ⚔&#xfe0f;🗡 |  |  |
| Wrestling | &#x1f93c; |  |  |  |
| Martial Arts |  | 🥋 |  |  |
| Skiing | ⛷🏂 | 🎿 |  |  |
| Surfing | 🏄 |  |  |  |
| Ice Skating |  |  | 🏐 |  |
| Biking / Cycling | 🚴 | 🚲 |  |  |
| Mountain Biking | 🚵 |  | ⛰ 🏔 |  |
| Riding | 🏇 | 🐎🐴 |  |  |
| Running | 🏃 | 👟🎽 | 💨 |  |
| Racing | 🏍 | 🏍🏎 | 🛣 | 🏁 |
| Weightlifting | 🏋 |  |  |  |
| Gymnastics | &#x1f938; |  |  |  |

**Comment by Crissov** [comment]
PS: Facebook’s original [Shark 🦈](http://emojipedia.org/shark/) emoticon `(^^^)` just represented mouth and teeth (→ _Jaws_) and thus their picture was ![just showing a shark’s wide-open mouth](https://slangit.com/img/sc/facebook/shark.png). I’d like to have that and the classic dorsal fin in waves `~~~/\\~~~` as well. A font could automatically trigger the latter in a sequence like🦈 🏊 or 🦈🏄 … `____/\___\o/___`.

Also, how about alternate graphics for U+1F40B 🐋 and 🐳 U+1F433 showing just a whale tail and a water fountain, respectively, (with waves) which would go nicely with boat emojis, 🚣⛵️🛥🚤⛴🛳?

**Comment by caseyahenson** [comment]
Moved to emojione-assets.
