### ISSUE TITLE
Animated Images

### ISSUE THREAD

**Issue by Crissov** [emojione/emojione#420]
Several original emojis were shown as animated GIFs by some Japanese telcos at least. It would be nice to get *optional* animations in modern emojis as well. Emoticons in chat apps and web forum software were also often animated, as are some stickers today.

## Examples

* [Softbank](http://cgi.wap2.jp/emoji/softbank/) (AGIFs)
* [KDDI au](http://www.au.kddi.com/ezfactory/tec/spec/pdf/typeD.pdf) (static PDF with all still frames)

**Comment by Fastidious** [comment]
That would be horrible! I sure hope animations do not make it to Emoji [ever again, assuming they once were].

**Comment by scakemyeranasshole** [comment]
For the :heart: of :2: NO! 

Use more words or imagination.  Spare us from aniGIF

**Comment by Crissov** [comment]
From _The Unicode Standard 9.0_ Chapter 22.9 _Miscellaneous Symbols_, page 806: 

> - Animation: Some characters in an emoji context are presented in animated
form, usually as a repeating sequence of two to four images.

**Comment by marsjaninzmarsa** [comment]
Subtle, not-looped, opt-in animation could be pretty nice.

**Comment by caseyahenson** [comment]
Moved issue to emojione-assets.
