### ISSUE TITLE
i18n? Is there a way to localize at least the "section titles" in the emoji-dropdown, e.g. "Food", "Smileys & People", "Recent" and etc.?

### ISSUE THREAD

**Issue by mep253** [emojione/emojione#483]
Is there a way to localize at least the "section titles" in the emoji-dropdown, e.g. "Food", "Smileys & People", "Recent" and etc.?

**Comment by caseyahenson** [comment]
@mep253 I think this would need to be handled through the related project. This sounds like emojione-picker maybe?
