### ISSUE TITLE
JS: Some emoji not converted by unicodeToImage

### ISSUE THREAD

**Issue by dbrgn** [emojione/emojione#496]
For example the white flag (U+1f3f3) without variation selector (U+FE0F):

```javascript
> emojione.unicodeToImage('🏳')
"🏳"
```

It seems to work when enabling greedy match:

```javascript
> emojione.greedyMatch = true
> emojione.unicodeToImage('🏳')
"<img class="e1" alt="🏳️" title=":flag_white:" src="img/e1/1f3f3.png"/>"
```

...or when appending the variation selector U+FE0F.

This is the entry in `emoji.json`:

```json
"1f3f3": {
    "name": "white flag",
    "category": "flags",
    "order": 2115,
    "display": 1,
    "shortname": ":flag_white:",
    "shortname_alternates": [
        ":waving_white_flag:"
    ],
    "ascii": [],
    "diversity": null,
    "diversities": [ ],
    "gender": null,
    "genders": [ ],
    "code_points": {
        "base": "1f3f3",
        "output": "1f3f3",
        "default_matches": [
            "1f3f3-fe0f"
        ],
        "greedy_matches": [
            "1f3f3-fe0f"
        ],
        "decimal": ""
    },
    "keywords": [
        "waving"
    ]
}
```

Is this intended? If yes, what should an emoji selector output when choosing the white flag? I assumed that either the map key or `.code_points.output` could be used. But they both don't contain the variation selector 16.

**Comment by codefuhrer** [comment]
#487

**Comment by dbrgn** [comment]
Any ETA on this, @caseyahenson? This is blocking Emojione 3 integration for Threema Web :slightly_smiling_face:

**Comment by caseyahenson** [comment]
@dbrgn one way to deal with this would be to turn greedy matching on, and when doing so use the zero index of `greedy_matches` as your output. For the most part greedy matching won't cause issues with replacement but will increase the number of matches for those like white flag and many others where `Emoji_Presentation=No` but in practice they are almost always intended to be emoji.

Do you think a solution like that could work for you?

**Comment by dbrgn** [comment]
That might work.

If there are multiple entries in `greedy_matches` (e.g. for "victory hand: medium-dark skin tone"), is the order significant? Can I rely on the first one being the appropriate codepoint(s)?

**Comment by caseyahenson** [comment]
There's no specific order for `greedy_matches`, and I'll have to run testing to be 100% sure that it wouldn't be problematic to always use the zero index as your output. 

The other thing is that if you're using the `output` property from emoji.json to generate native unicode (say via an emoji picker) and using the library to convert to images (with `greedyMatch = true`) you should be good to go. I think that we need to make a few minor changes to the special cases in the emoji.json file to more appropriately reflect how we're handling them in the conversion scripts.

**Comment by dbrgn** [comment]
My "fear" is: will greedy matching also convert things like ™ or ® without the variation selector U+FE0F? We got complaints in the past from users that didn't want those converted to emoji.

Maybe using greedy matching on the output from the picker, but non-greedy matching on the generated messages (yes, we convert the emoji to native unicode), could work, since the picker would then always include the emoji variation selector, right?

**Comment by caseyahenson** [comment]
If I understand correctly, I think that solution would work. Greedy matching will attempt to replace trademark/copyright/registered without VS16, which actually might be something that needs to be removed again, given the conflict that we're finding now with other emoji that still need greedy matching. We may push a fix for tm/copy/reg and a couple of other things within the next few days that will help straighten this out.

**Comment by dbrgn** [comment]
Ok, that seems to work. Right now I had to enable greedy matching everywhere, but the goal is that all involved clients set the u+fe0f variant selector when sending emoji. Once that's the case greedy matching can be turned off again.
