### ISSUE TITLE
Is emoji awesome available on cdn somewhere for ver 3?

### ISSUE THREAD

**Issue by mika76** [emojione/emojione#500]

**Comment by mjfwebb** [comment]
Links are here: https://github.com/Ranks/emojione/blob/master/INSTALLATION.md

**Comment by mika76** [comment]
I do not see emotions awesome 3 there?

**Comment by mjfwebb** [comment]
Sorry I actually misread your question. I looked and can't find the emoji awesome cdn for ver 3.

**Comment by mika76** [comment]
Yeah me neither 😢 is it not supported any more? Is planned for a future release?

**Comment by caseyahenson** [comment]
@mika76 we can make that happen :)

**Comment by mika76** [comment]
It would be the height of awesome 😊

**Comment by kevinranks** [comment]
Should be available now: https://cdn.jsdelivr.net/npm/emojione@3.1.2/lib/emojione-awesome

**Comment by mika76** [comment]
@kevinranks thank you so much!

**Comment by mika76** [comment]
@kevinranks There is no css file? Have to use javascript?

**Comment by kevinranks** [comment]
@mike76, check out the README.md in that folder:

### How to generate mapping

```
cd lib/emojione-awesome
node generate.js

```

### How to compile scss

Once you've generated the mapping you can build the css files via grunt.
The compiled styles are output into /extras/css/emojione-awesome.css

```
npm install grunt grunt-contrib-sass
grunt sass
```

**Comment by mika76** [comment]
@kevinranks yeah I saw, but it kinda defeats the purpose of a cdn which is to just link in your html and go...

**Comment by mika76** [comment]
@kevinranks If you look at https://cdnjs.cloudflare.com/ajax/libs/emojione/2.2.7/assets/sprites/emojione.sprites.css before there was a full .css that could just be linked in an html file and you could use the sprites directly.

**Comment by kevinranks** [comment]
@mika76 My apologies, have a look at  https://cdn.jsdelivr.net/npm/emojione@3.1.2/extras/css/emojione-awesome.css

**Comment by kevinranks** [comment]
There's also the sprite css:

https://cdn.jsdelivr.net/emojione/assets/3.1/sprites/emojione-sprite-32.css

taken from:

https://github.com/emojione/emojione-assets/tree/master/sprites

**Comment by mika76** [comment]
@kevinranks Thaaaaat's what I'm talking about 😄  thanks a million!
