### ISSUE TITLE
"White medium star" is yellow

### ISSUE THREAD

**Issue by madgnome** [emojione/emojione#502]
The `:star:` emoji has the name "White medium star" but the star is yellow. Should the name be changed to "Medium star" or alike?

**Comment by JoshyPHP** [comment]
`WHITE MEDIUM STAR` is the name of the character in Unicode's database. It's usually displayed as a yellow star. Similarly, `HEAVY BLACK HEART` is usually pictured as a red heart. Back when those characters were created, fonts were monochrome so a yellow star would appear white and a red heart would be black.

- http://www.unicode.org/Public/UNIDATA/NamesList.txt
- http://emojipedia.org/white-medium-star/
- http://emojipedia.org/heavy-black-heart/

**Comment by madgnome** [comment]
Emojione 3.0 doesn't stick to the Unicode name for a lot of emoji

- :telephone: is called "Telephone" and not "Black telephone"
- :relaxed: is called "Smiling" and not "White smiling face"
Even heavy black heart doesn't have a discrepancy anymore in emoji 3.0

**Comment by dbrgn** [comment]
See also: #499

**Comment by caseyahenson** [comment]
In previous versions we would often customize the titles and shortnames, usually to shorten or simplify them, but as of recently we're using a lot more consistency with the titles that Unicode provides. We may be adding more alternate shortnames at some point for any of the older emoji to make matching more consistent.
