### ISSUE TITLE
unicodeRegexp and cacheBustParam gone in 3.x

### ISSUE THREAD

**Issue by suprMax** [emojione/emojione#505]
I was using unicodeRegexp property in my project's codebase to parse content and replace unicode with emojis in large chunks of text (complex content parsing rules).

I noticed that it's gone in 3.x release. Is there any equivalent replacement for it? I couldn't come up with anything short of extracting the old regex from the 2.x or getting locked to 2.x release.

Additionally I noticed that cache busting is missing in this release. Is it intentional or will it be back at some point?

**Comment by caseyahenson** [comment]
@suprMax we're using range matching in v3 which is now built into `regUnicode`. You should be able to use it alongside some post-match filtering to get what you're looking for, similar to how it's done in unicodeToImage(): https://github.com/emojione/emojione/blob/master/lib/js/emojione.js#L315. Hopefully that's what you're looking for and if not let me know and I'm sure we can figure something out.

The cache bust param was removed and replaced by CDN versioning, as in https://cdn.jsdelivr.net/emojione/assets/3.0/png/64/1f600.png. We're currently on 3.0 and will increment to 3.1 for our Unicode 10 release, for example.

**Comment by suprMax** [comment]
No, unfortunately they are not interchangeable as previous was matching only a single emoji and new regex matches as many as it can. However I think I can generate old regex from the emoji.json file as a workaround.

**Comment by caseyahenson** [comment]
You could definitely build an exact match regex from the emoji.json data. I'm going to paste some old code that we used to build the unicodeRegexp with. This has been untested beyond Emoji 3.0 but it should still be valid. The basic usage was something like:

```
var temp = [];
...loop through output code points {
    var str = convertCharStr2jEsc(outputCodePoint);
    temp.push(str.replace(/\\u/g,'\\\\u'));
}
```
Then the `temp` array should be sorted largest to smallest for accurate matching, and of course then joined with a pipe. Here's the code:

```
function convertCharStr2jEsc (str) {

        var cstyle = false;

        // Converts a string of characters to JavaScript escapes
        // str: sequence of Unicode characters

        var highsurrogate = 0;
        var suppCP;
        var pad;
        var n = 0;

        var outputString = '';
        for (var i = 0; i < str.length; i++) {
            var cc = str.charCodeAt(i);
            if (cc < 0 || cc > 0xFFFF) {
                outputString += '!Error in convertCharStr2UTF16: unexpected charCodeAt result, cc=' + cc + '!';
            }
            if (highsurrogate != 0) { // this is a supp char, and cc contains the low surrogate
                if (0xDC00 <= cc && cc <= 0xDFFF) {
                    suppCP = 0x10000 + ((highsurrogate - 0xD800) << 10) + (cc - 0xDC00);
                    if (cstyle) {
                        pad = suppCP.toString(16);
                        while (pad.length < 8) { pad = '0'+pad; }
                        outputString += '\\U'+pad;
                    }
                    else {
                        suppCP -= 0x10000;
                        outputString += '\\u'+ dec2hex4(0xD800 | (suppCP >> 10)) +'\\u'+ dec2hex4(0xDC00 | (suppCP & 0x3FF));
                    }
                    highsurrogate = 0;
                    continue;
                }
                else {
                    outputString += 'Error in convertCharStr2UTF16: low surrogate expected, cc=' + cc + '!';
                    highsurrogate = 0;
                }
            }

            if (0xD800 <= cc && cc <= 0xDBFF) { // start of supplementary character
                highsurrogate = cc;
            }
            else { // this is a BMP character

                //outputString += dec2hex(cc) + ' ';

                switch (cc) {
                    case 0: outputString += '\\0'; break;
                    case 8: outputString += '\\b'; break;
                    case 9: outputString += '\\t'; break;
                    case 10: outputString += '\\n'; break;
                    case 13: outputString += '\\r'; break;
                    case 11: outputString += '\\v'; break;
                    case 12: outputString += '\\f'; break;
                    case 34: outputString += '\\\"'; break;
                    case 39: outputString += '\\\''; break;
                    case 92: outputString += '\\\\'; break;

                    default:
                        if (cc > 0x1f && cc < 0x7F) { outputString += String.fromCharCode(cc); }
                        else {
                            pad = cc.toString(16).toUpperCase();
                            while (pad.length < 4) { pad = '0'+pad; }
                            outputString += '\\u'+pad;
                        }
                }
            }
        }
        return outputString;
    }



    function  dec2hex4 ( textString ) {

        var hexequiv = new Array ("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F");

        return hexequiv[(textString >> 12) & 0xF] + hexequiv[(textString >> 8) & 0xF]

            + hexequiv[(textString >> 4) & 0xF] + hexequiv[textString & 0xF];

    }
```

Also, there's definitely a gap in our docs regarding the emojione-assets change so thanks for pointing that out.

**Comment by suprMax** [comment]
I think this should work for us, thank you!

**Comment by suprMax** [comment]
@caseyahenson could you help me out a bit more please?

From what I understood I need to first convert what's in `code_points.output` with a function like https://github.com/emojione/emojione/blob/master/lib/js/emojione.js#L398 to a unicode character, and then get it escaped with `convertCharStr2jEsc` that you shared. Is there a direct string to escaped string method? I couldn't find any build tools, but you must have it somewhere to generate this: https://github.com/emojione/emojione/blob/master/lib/js/emojione.js#L22

Also you mentioned sorting. I get strings like `\uD83D\uDEB5\u200D\u2642\uFE0F`, I take it you meant simply sorting by length and then `new RegExp(parts.join('|'))`?

**Comment by caseyahenson** [comment]
@suprMax you're correct it will need to be run through the convert function first to generate unicode from the output code point, looks like I missed that step in my previous comment. We use a multi-step process to generate any escaped unicode you see in our libraries. As for sorting you're also correct, sort by escaped string length descending order before joining into a regex, which prevents diverse/gendered code points from being partially matched as their non-diverse/non-gendered counterpart.

**Comment by suprMax** [comment]
After spending a ridiculous amount of time reading through source of https://github.com/twitter/twemoji/blob/gh-pages/twemoji-generator.js and recreating it, I stumbled upon https://github.com/mathiasbynens/emoji-regex which seems to do exactly what I need in a most elegant form. I will stick with that module and I hope my comment saves someone time.
