### ISSUE TITLE
Add full codepoints in addition to base codepoints to extras/alpha-codes

### ISSUE THREAD

**Issue by maximbaz** [emojione/emojione#511]
I'm using [alpha-codes](https://github.com/emojione/emojione/tree/master/extras/alpha-codes) for creating an emoji autocomplete feature for some app, however both `json` and `csv` files only mention base codepoints and not full codepoints. 

I cannot properly render emoji glyph using only base codepoints. It would be _extremely helpful_ to add another column / field to both `csv` and `json` files declaring full code points.

For `csv`:

Before:

```
"unicode","name","alpha code","aliases"
"1f468-1f466-1f466","family: man, boy, boy",":family_man_boy_boy:",""
```

After:

```
"unicode","unicode_full","name","alpha code","aliases"
"1f468-1f466-1f466","1f468-200d-1f466-200d-1f466","family: man, boy, boy",":family_man_boy_boy:",""
```

For `json`:

Before:

```
    "1f468-1f466-1f466": {
        "name": "family: man, boy, boy",
        "alpha code": ":family_man_boy_boy:",
        "aliases": ""
    },
```

After:

```
    "1f468-1f466-1f466": {
        "name": "family: man, boy, boy",
        "alpha code": ":family_man_boy_boy:",
        "full codepoints": "1f468-200d-1f466-200d-1f466",
        "aliases": ""
    },
```

------------

@caseyahenson you mentioned the following in the android font discussion:

> @maximbaz the correct output for those is found in the emoji.json file. That data is structured with what we refer to as the "base codepoint" (stripped of ZWJ and VS16) as the key, and you can map to the code_points.output property using the file names found in the emojione-assets directory as the base codepoint.

So the data is available, it's just in a different file. I assume the `extras/alpha-codes` was not created by hand, but generated with some script, if so, could you please add this modification to the script and regenerate both `csv` and `json` files? Alternatively I could create a simple script to add this data to the files based on `emojione-assets/emoji.json` file.

**Comment by maximbaz** [comment]
Just found https://github.com/emojione/emoji-alpha-codes/pull/3, I don't know if the base codepoints are of any use without ZWJ in these files, if no - maybe that one is even better approach?

**Comment by maximbaz** [comment]
@caseyahenson a friendly ping on the issue, would you merge the PR if I add `full codepoints` to the json and csv files in [alpha codes](https://github.com/emojione/emojione/tree/master/extras/alpha-codes)?

**Comment by caseyahenson** [comment]
@maximbaz we'll be pushing a 3.1 update tomorrow and I'll make sure to include the full output code point in the alpha codes data.

**Comment by maximbaz** [comment]
Thank you for this! 🙂
