### ISSUE TITLE
`:levitate:` shortcode is not matched by the parser?

### ISSUE THREAD

**Issue by suprMax** [emojione/emojione#512]
This is supplied by emojis.json: `"1f574":{"name":"man in business suit levitating","category":"people","order":895,"display":1,"shortname":":levitate:","shortname_alternates":[],"ascii":[],"diversity":null,"diversities":["1f574-1f3fb","1f574-1f3fc","1f574-1f3fd","1f574-1f3fe","1f574-1f3ff"],"gender":null,"genders":[],"code_points":{"base":"1f574","output":"1f574","default_matches":["1f574-fe0f"],"greedy_matches":["1f574-fe0f"],"decimal":""},"keywords":["business","man","suit"]}`

It seems it is supposed to be `"1f574":{"name":"man in business suit levitating","category":"people","order":895,"display":1,"shortname":":man_in_business_suit_levitating:","shortname_alternates":[],"ascii":[],"diversity":null,"diversities":["1f574-1f3fb","1f574-1f3fc","1f574-1f3fd","1f574-1f3fe","1f574-1f3ff"],"gender":null,"genders":[],"code_points":{"base":"1f574","output":"1f574","default_matches":["1f574-fe0f"],"greedy_matches":["1f574-fe0f"],"decimal":""},"keywords":["business","man","suit"]}`

**Comment by suprMax** [comment]
![screen shot 2017-07-05 at 1 42 01 pm](https://user-images.githubusercontent.com/789031/27862872-be8669b6-6187-11e7-8542-45a4b06e07cb.png)

**Comment by kevinranks** [comment]
I've updated the shortnames... `:levitate:` should be a shortname in future releases.
