### ISSUE TITLE
Future of Emoji One now that Google (Android) has come to it's senses?

### ISSUE THREAD

**Issue by kq01526** [emojione/emojione#515]
@thinkrick :

No offense, but:

Now that [Google (Android) has finally come to it's senses in regards to their Emoji design (finally dropping the blobs)](http://blog.emojipedia.org/rip-blobs-google-redesigns-emojis/), what are the plans for Emoji One?

Looks like they're also going to open source [the new design](http://emojipedia.org/google/android-o-beta/), see:

https://github.com/googlei18n/noto-emoji/issues/141

Do we even still need Emoji One anymore (again, no offense, just thinking out aloud)?

**Comment by dasbaumwolltier** [comment]
Now we need them more than ever
The new emojis are just awful
