### ISSUE TITLE
Emojione is not displayed on Samsung S5. Instead displayed native emoji.

### ISSUE THREAD

**Issue by Procurares** [emojione/emojione#519]
I'm trying to use emojione in my application by integrating it as font. I don't want to replace system font, or use any third party applications. I want it to have only inside my application

```
override fun bindViewHolder(adapter: FlexibleAdapter<out IFlexible<*>>, holder: ViewHolder, position: Int, payloads: MutableList<Any?>?) {
        holder.contentView.onClick {
            listener.onEmojiClicked(position)
        }

        holder.emojiTextView.typeface = emojiOneTypeface(context)
        holder.emojiTextView.text = emojiCode
    }

fun emojiOneTypeface(context: Context): Typeface {
    val typeface = Typeface.createFromAsset(context.resources.assets, "fonts/emojione.ttf")

    return typeface
}
```

Everything is displayed correctly on my Nexus 5X, default Google Emoji are replaced with pretty EmojiOne. 
But this replacement doesn't apply on Samsung S5(i believe on others too). Samsung displays it native emojis. 
What kind of issue it could be? 
Is there any other way of integrating emojione as font into application?

**Comment by caseyahenson** [comment]
This sounds like an issue we've seen reported in the past. I think this is possible but you'll need to consult some Android development threads to as I think this is a bit off topic for the scope of this repo. Something like this might help steer you in the right direction: https://stackoverflow.com/questions/6926263/add-custom-font-for-complete-android-application.

Good luck!
