### ISSUE TITLE
:star_truck: image link not loading (v3.1.0)

### ISSUE THREAD

**Issue by mroftalp** [emojione/emojione#521]
:star_struck: image link not working https://cdn.jsdelivr.net/emojione/assets/3.1/png/64/1f929.png 

But /32/ is working. 👍

**Comment by caseyahenson** [comment]
@mroftalp do you receive an error message on that page? It loads okay for me on desktop and mobile. Can you check a couple different images, like 
 https://cdn.jsdelivr.net/emojione/assets/3.1/png/64/1f600.png and 
 https://cdn.jsdelivr.net/emojione/assets/3.1/png/64/1f9d9.png?

**Comment by mroftalp** [comment]
Apologies for not able to send the screenshot of the error. Here you go:

![image](https://user-images.githubusercontent.com/6789191/27757729-f28a5914-5e37-11e7-8fa2-3a04e1895eec.png)

**Comment by mroftalp** [comment]
The two images you asked me to check loads ok. :)

**Comment by mroftalp** [comment]
Seems to be ok now.

**Comment by caseyahenson** [comment]
Glad to hear!
