### ISSUE TITLE
In emoji.json the `genders` array for emojis with genders is always [null, null]

### ISSUE THREAD

**Issue by lepolt** [emojione/emojione#528]
Emojis without a gender option just has an empty array... I was under the assumption (as documented in UPGRADE.md), that the `genders` array would "contain the base code points of the gender children for a gender parent (gender-neutral, gender base)."

For example, 
"1f482": {
  "name": "guard",
  "gender": null,
  "genders": [null, null]
}
"1f482-2642": {
  "name": "man guard",
  "gender": "2642",
  "genders": []
}
"1f482-2640": {
  "name": "woman guard",
  "gender": "2640",
  "genders": []
}

**Comment by caseyahenson** [comment]
@lepolt thanks for pointing this out, it's definitely intended to be the primary key of the gender children. We'll be pushing an update to that file in the next day or two to fix the issue.

**Comment by caseyahenson** [comment]
This is resolved in the 3.1.1 update.
