### ISSUE TITLE
`viewBox` missing from v3.1 SVGs

### ISSUE THREAD

**Issue by workmanw** [emojione/emojione#529]
I'm not sure if this is the right place to report this issue, but we purchased the v3.1 SVGs and found that the `viewBox` attribute is missing from the SVG tag on all of the emojis. This causes scaling issues on Internet Explorer browsers. 

Also, v2.2 SVGs had `viewBox`. See: [2.2.7/assets/svg/0023-20e3.svg](https://raw.githubusercontent.com/emojione/emojione/2.2.7/assets/svg/0023-20e3.svg).

**Comment by caseyahenson** [comment]
@workmanw we did make the decision to remove the viewBox attribute as of 3.0. Our reasoning was to decrease the overall size of the assets, and in applications we do ultimately end up including that attribute back into the markup. If that's not something that makes sense for your application let us know what limitations you face so we can determine how to best approach the situation for future releases.

**Comment by workmanw** [comment]
Hey @caseyahenson Thanks for the quick response. So the part of our application where we use emojione is like a whiteboarding tool. Here is a screenshot:

![image](https://user-images.githubusercontent.com/825487/27935401-eed68c9e-6278-11e7-9575-352b2e0f4206.png)

We allow users to resize emojis to as big or small as they want. That is the appeal for using SVGs over sprites). In the DOM we insert these emojis as `<img src="XXX.svg">` rather than use object. 

The problem is that because these SVGs have width/height instead of viewbox, it prohibits them from scaling on Internet Explorer. I could not find any formal documentation on this, but you'll find dozens of SO issues where people ask about this. Here is one such example: https://stackoverflow.com/questions/27970520/svg-with-width-height-doesnt-scale-on-ie9-10-11

Honestly it's not a huge deal. I was planning to write a node script to parse and rewrite these SVG files to have `viewBox`. I just wanted to call it out as an issue to make sure it wasn't a regression.

**Comment by caseyahenson** [comment]
I see, thanks for explaining. Let us know how it goes with the rewrite and if that's something you think is sustainable for you for future updates. I'm going to close this issue out but shoot us a message at support@emojione.com or open another issue here or at the emojione-assets repo if you have any questions.

That project looks awesome by the way :)

**Comment by workmanw** [comment]
@caseyahenson Thanks a lot. The script was straightforward. I figured I'd paste it here in case anyone else wants to use it.

```javascript
#!/usr/local/bin/node

const fs = require('fs')

const FILE_PATH = 'apps/bootstrap/vendor/emojione/svgs'

function extractSVGDimension(str, dimension, filePath) {
  let match = str.match(`<svg[^>]*${dimension}="([0-9]+)"`);
  if (!match) {
    console.warn(`Warning: Did not find dimension \`${dimension}\` in file: "${filePath}".`);
  }
  return match ? match[1] : null;
}

function applyViewboxToSVG(filePath) {
  fs.readFile(`${filePath}`, 'utf8', (err, fileContents) => {
    if (!fileContents.match('<svg[^>]*viewBox')) {
      let width = extractSVGDimension(fileContents, 'width', filePath);
      let height = extractSVGDimension(fileContents, 'height', filePath);

      let updatedFile = fileContents.replace(/(<svg[^>]*)>/, `$1 viewBox="0 0 ${width} ${height}">`);
      fs.writeFile(filePath, updatedFile, err => {
        if(err) {
          console.error(err);
        }
      });
    }
  });
}

fs.readdir(FILE_PATH, (err, files) => {
  if (typeof files) {
    files.forEach(file => {
      applyViewboxToSVG(`${FILE_PATH}/${file}`);
    });
  }
});
```

On a final note, we've been really happy with emojione so far. Keep up the great work and thanks for being so response to this issue and the other ones we've filed.
