### ISSUE TITLE
Incorrect images loaded from sprites

### ISSUE THREAD

**Issue by emanuelcostea** [emojione/emojione#533]
There are differences between emojis from sprites and the full list from `emojioneList` variable. 
I am trying to list all the emojis and use the sprites for the images, using `uc_base` variable to get the code and link to the sprite css class. I was trying to use the other uc variables but I get same results. Maybe I am missing something here.

I get this problem on `emojione-assets 3.1.0` and latest version of `emojione`.

**Comment by kevinranks** [comment]
@emanuelcostea We recommend that you use the [emoji.json data file](https://cdn.jsdelivr.net/npm/emojione@3.1.2/emoji.json) provided when you need to display emoji. It contains important metadata such at the category & sort order.

**Comment by frangeris** [comment]
@kevinranks [emoji.json](https://cdn.jsdelivr.net/npm/emojione@4.0.0/emoji.json) its to big, so I start using the [emoji_strategy.json](https://github.com/emojione/emojione/blob/master/emoji_strategy.json) but there is not emoji category, `emoji_strategy` doesnt have it and its required to render emojis without script....


Any chance to add the category to each emoji in `emoji_strategy` file?

Thanks
