### ISSUE TITLE
T-Rex pose not scientifically accurate

### ISSUE THREAD

**Issue by salty-horse** [emojione/emojione#536]
The EmojiOne image for U+1F996 T-REX shows it nearly upright. While this is a popular look for the dinosaur, it does not reflect current scientific understanding. "Canonizing" it in an emoji will help perpetuate the myth.

For more info:
https://en.wikipedia.org/wiki/Tyrannosaurus#Posture
http://news.cornell.edu/stories/2013/02/blame-barney-students-perception-t-rex-outdated

**Comment by kevinranks** [comment]
Moved this issue to the correct repo: 
[T-Rex pose not scientifically accurate #29](https://github.com/emojione/emojione-assets/issues/29)
