### ISSUE TITLE
ascii To Unicode function 

### ISSUE THREAD

**Issue by fzp01717** [emojione/emojione#564]
Hello, i am working on nodejs. i have a query. is there any function is present name asciiToUnicode for ascii To Unicode convert. thanks

**Comment by Davidc2525** [comment]
I did. you just have to do a new strategy and use it

import findWithRegex from 'find-with-regex';
import emojione from 'emojione';
  //-----------------------------------------------------| use to RegExp by ascii
const unicodeRegex = new RegExp (emojione.asciiRegexp, 'g');

export default (contentBlock: Object, callback: Function) => {
   findWithRegex (unicodeRegex, contentBlock, callback);
};
