### ISSUE TITLE
[JS] Almost all functions don't work with (Vue) Webpack

### ISSUE THREAD

**Issue by daniandl** [emojione/emojione#589]
I use Vue PWA which is based off of Vue Webpack.

If i try to run `console.log(emojione.toImg('test'))` I get a console error saying str.replace is not a function. Same problem happens with all the conversion functions I've tested so far. 

Some research led me to believe it was the uglify-es package that needed updating, this didn't change anything. If anyone has a fix for a webpack oriented environment please help!

Cheers

**Comment by Maarethyu** [comment]
![1519903900427](https://user-images.githubusercontent.com/11776438/38805194-4207ce06-4175-11e8-81b0-783d495eaff1.jpg)
