### ISSUE TITLE
blacklistChars getting ignored

### ISSUE THREAD

**Issue by jastend** [emojione/emojione#598]
Tested with the JS version and PHP version. The blacklistChars option seems to get ignored.

JS Example:

```
window.emojione = require('emojione');
window.emojione.blacklistChars = '*,#';

return window.emojione.toImage('*');
```

Observed result:

```
<img class="emojione" alt="*" title=":asterisk_symbol:" src="https://cdn.jsdelivr.net/emojione/assets/3.1/png/32/002a.png"/>
```

Expected result:

```
*
```

**Comment by jannikweise** [comment]
I also have the problem that the characters "#" and "*" are replaced by emojis. The solution with the blacklistChars does not work in the current version, because the list was removed in version 3.1.5.

Why was the blacklistChars property removed and is there another solution for this problem?

**Comment by abdelhady** [comment]
I have the same problem with the latest php version

**Comment by caseyahenson** [comment]
This should be repaired in today's 3.1.7 release.
