### ISSUE TITLE
[php] `#` & `*` are recognized as emojis while they should not

### ISSUE THREAD

**Issue by abdelhady** [emojione/emojione#599]
I'm using the following code to translate emojis to their shortnames:
```php
function getShortText($text) {
    $emojiClient = new \Emojione\Client(new \Emojione\Ruleset());
    return $emojiClient->toShort($text);
}
```
using your latest version `3.1.5`

now if I used this function like:
`getShortText("Hello #world from Mr.*")`

I get this response
`Hello :pound_symbol:world from Mr.:asterisk_symbol:`
while I should get the following text instead:
`Hello #world from Mr.*`

& I read the `Client()` & `Ruleset()` sourcecodes & I can't find anything to disable this weird behavior !!

**Comment by ShobhanaMarkeshan** [comment]
I'm using the following code to translate emojis to their images:

```
function convert() {
    var input = document.getElementById('inputText').value;
    var output = emojione.unicodeToImage(input);
    document.getElementById('outputText').innerHTML = output;
  }
```

using your latest version 3.1.6

(https://demos.emojione.com/latest/jsunicodetoimage.html)

even i am facing the same problem.. 

can some one help out.. Thank you in advance..

**Comment by Benxter83** [comment]
Yeah, we have the same problem. Apparently with minor release 3.1.4 this was introduced. For now we downgraded to 3.1.3 which doesn't have the problem. All digits are also affected btw.

**Comment by Benxter83** [comment]
According to the commit for 3.1.4 it seems that a downstream dependency is causing this. But this should have been caught before releasing by proper testing.....

**Comment by xosofox** [comment]
Same issue on our end, downgrade to 3.1.4 helps for the moment

**Comment by Benxter83** [comment]
@EmojiOne I understand that this "issue" is actually an feature but then you should have introduced this into a major/minor version and not as a patch version because this is now a breaking change...

**Comment by ShobhanaMarkeshan** [comment]
@Benxter83 after downgrading to 3.1.4. the below code snippet is not returning any emoji images

```
  convert() {
    let input = (<HTMLInputElement>document.getElementById('inputText')).value;
    let output = emojione.unicodeToImage(input);
    document.getElementById('outputText').innerHTML = output;
  }
```

![emoji](https://user-images.githubusercontent.com/20458112/42551731-5d7a860a-84f6-11e8-8d04-15e2a849f018.png)

**Comment by ShobhanaMarkeshan** [comment]
@Benxter83  I have downgraded from 3.1.6 to 3.1.4. but then the below code snippet is not returning any emoji images.

```
<script type="text/javascript">
function convert() {
    var input = document.getElementById('inputText').value;
    var output = emojione.unicodeToImage(input);
    document.getElementById('outputText').innerHTML = output;
  }
</script>
<body>
    <div class="emoji-test">
       <input type="text" id="inputText" name="inputText" value=" Hello #world from Mr.*  ☺ ☺ ☺">
       <input type="button" value="Convert" (click)="convert()">
       <p id="outputText"></p>
   </div>
</body>
```


![emoji](https://user-images.githubusercontent.com/20458112/42553225-a0b17c06-84fd-11e8-9ab1-f792aff2e8b5.png)

**Comment by ShobhanaMarkeshan** [comment]
If i downgrade from 3.1.6 to 3.1.4. I am facing the below problem. Any solution will be appreciated.
![emojierr](https://user-images.githubusercontent.com/20458112/42555005-86d7f074-8504-11e8-8ba7-06b817ab6084.png)

**Comment by ankero** [comment]
If you have been using the toShort() function with markdown, I highly recommend doing a manual check what else this function has broken. For us this broke our whole markdown, mentions, links, everything that had numbers and special characters, and of course in web app + in mobile app. 

We are currently doing a migration function to revert every character this library has converted in our DB since the bug was introduced. So... yeah...

**Comment by caseyahenson** [comment]
These bugs are repaired in today's 3.1.7 release. Our apologies for the trouble this oversight caused.
