### ISSUE TITLE
digits and simple characters are converted to emojis in ´toShort´

### ISSUE THREAD

**Issue by xosofox** [emojione/emojione#600]
same as #599 but not only affects PHP.
JS conversion is affected, too

It was ok in 3.1.4

If this is supposed to be introduced as a feature, semver (https://semver.org/) would strictly speak against the approach of introducing it in a minor version update

Semver is

😲 . 😄 . 🤒 

not

😲 . 😄 . 😨

**Comment by ankero** [comment]
We found the same issue as well and froze the package version to 3.1.2. Honestly changing digits to :digit_five: etc. is very very stupid and a breaking change. So please don't mark these kinds of changes as patches.

**Comment by caseyahenson** [comment]
The replacement of non-emoji components is fixed in the 3.1.7 release.
