### ISSUE TITLE
Links get destroyed by "strtoupper($unicode = $m[0]);"

### ISSUE THREAD

**Issue by Enaah** [emojione/emojione#602]
Hi, 

I'm using [Laravel Emojione](https://github.com/christofferok/laravel-emojione) to use this Lib in my Laravel Application (Blog).

I'm rendering the whole Content-Part with this Statement:
```blade
{!! LaravelEmojiOne::toImage($post->content_html) !!}
```

Since Version 3.0 there is this line:
https://github.com/emojione/emojione/blob/147c4070d4eda43e057c2331e2f5264f4b60bdf9/lib/php/src/Client.php#L455

Which takes some Attributes from the <a>-Tage (for example the link) and makes it uppercase (and breaks it).

Why is this line needed? When I remove the "strtoupper" everything works fine.

**Comment by akshaykolhapure995c** [comment]
noticed

**Comment by caseyahenson** [comment]
This behavior is fixed in today's 3.1.7 release.
