### ISSUE TITLE
output: null in eac.json for EmojiOne 4

### ISSUE THREAD

**Issue by maximbaz** [emojione/emojione#612]
@caseyahenson I noticed in `eac.json` some `output` fields became `null`.

```
    "00a9": {
        "output": null,          <----------------------------------------
        "name": "copyright",
        "alpha_code": ":copyright:",
        "aliases": ""
    },
    "00ae": {
        "output": null,          <----------------------------------------
        "name": "registered",
        "alpha_code": ":registered:",
        "aliases": ""
    },
    "203c": {
        "output": null,          <----------------------------------------
        "name": "double exclamation mark",
        "alpha_code": ":bangbang:",
        "aliases": ""
    },
    ...
```

I'm relying on this field to properly render emojis, and previously they were correctly filled. Is this a bug in the tool used to generate this file?

![image](https://user-images.githubusercontent.com/1177900/44847618-62d29b80-ac54-11e8-8c52-795aea686017.png)

**Comment by caseyahenson** [comment]
@maximbaz good catch, I'll get this updated today

**Comment by maximbaz** [comment]
@caseyahenson I see you were updating the files, posting just in case you didn't notice, there are still some differences comparing to the file with emojione 3:

- `fe0f` is missing:

![image](https://user-images.githubusercontent.com/1177900/44884997-d610f780-acbe-11e8-8ae2-d56f8b712e45.png)

- code sometimes is wrong:

![image](https://user-images.githubusercontent.com/1177900/44885013-e923c780-acbe-11e8-8e0b-c8eebd4539a1.png)

**Comment by caseyahenson** [comment]
check these newest files, @maximbaz. These should be solid

**Comment by maximbaz** [comment]
Look perfect, thanks a lot!
