### ISSUE TITLE
Firefox extension - Page not found

### ISSUE THREAD

**Issue by raulcraveiro** [emojione/emojione#632]
The link for Firefox extension (https://www.emojione.com/apps/emoji-keyboard-extension) doesn't work, It says "Page not found". What happened with the extension? :(

**Comment by caseyahenson** [comment]
@raulcraveiro our Firefox extension is disabled for compatibility issues. We may explore releasing an updated version in the future.

**Comment by Darkhogg** [comment]
@caseyahenson Is there any way we can help with porting the extension to the current Firefox versions?
