### ISSUE TITLE
":p" in PHP Parser

### ISSUE THREAD

**Issue by Sjoerrdd** [emojione/emojione#640]
Hello,
When I type "hi :p", the [php parser](https://demos.emojione.com/latest/phptoimage.php#output) removes the space before the ":".
example: ![](https://i.gyazo.com/458b1d5b47e1ad40b7fb0124c11e03b5.png)

**Comment by caseyahenson** [comment]
@Sjoerrdd thanks! We'll have a fix for this published next week

**Comment by Sjoerrdd** [comment]
Thank you.
