### ISSUE TITLE
README.md for fonts contains broken links

### ISSUE THREAD

**Issue by ubergeek77** [emojione/emojione#643]
The README.md for [the mobile phone font files](https://github.com/emojione/emojione/tree/master/extras/fonts) was recently updated to contain links for the 4.5 release of those respective files. However, there are no 4.5 releases on the emojione-assets repository, so all of these links are now broken.

**Comment by caseyahenson** [comment]
Hi @ubergeek77 thanks for pointing this out, the files have been attached to the release.
